-- CreateTable
CREATE TABLE "UsageTable" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "bucketId" TEXT NOT NULL DEFAULT '',
    "from" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "to" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "total" INTEGER NOT NULL DEFAULT 0,
    "used" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "left" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "UsageTable_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "UsageTable" ADD CONSTRAINT "UsageTable_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
