-- AlterTable
ALTER TABLE "UsageTable" ALTER COLUMN "total" DROP NOT NULL,
ALTER COLUMN "total" SET DATA TYPE BIGINT,
ALTER COLUMN "from" SET DATA TYPE BIGINT,
ALTER COLUMN "to" SET DATA TYPE BIGINT;
